<body class="home blog">
<div class="inner">
<div id="page" class="hfeed">
<header class="head">
<nav id="access" role="navigation">
<li id="menu-item-3730" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-3730"><a href="http://www.loveluxeblog.com/advertise/">Advertise</a></li>
<li id="menu-item-343" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-343"><a href="http://www.loveluxeblog.com/submissions/">Write for Us!</a></li>
<li id="menu-item-302" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-302"><a href="http://www.loveluxeblog.com/contact/">Contact</a></li>
<li class="s"><a href="http://www.loveluxeblog.com/feed/" class="rss"></a></li>
<li class="s"><a href="http://twitter.com/LoveLuxeBlog/" class="twitter"></a></li>
<li class="s"><a href="http://www.facebook.com/LoveLuxeBlog/" class="facebook"></a></li>
<li class="s"><a href="http://www.pinterest.com/LoveLuxeBlog/" class="pinterest"></a></li>
<li class="menu-search"><form class="searchform" action="/" id="searchform-main" method="get">
<label class="assistive-text" for="search-word">Search</label>
<input type="text" placeholder="Search..." id="search-word" name="s" class="field" value="">
<input type="submit" value="Search" id="searchsubmit-main" name="submit" class="submit">
</form></li>
</ul>
</nav>
</header>
<div class="section-wrap"><div class="content-left"><div class="hero-wrap"><div class="home-heros"><article class="hero">
<a href="http://www.loveluxeblog.com/cakes-and-desserts-my-diy-wedding-cake/"><span class="r">Cakes and Desserts: My DIY wedding cake</span></a>
<img width="660" height="294" src="/cache/uploads/2013/02/hero-image-7753-660-LoveLuxe-Post01-BB-FeaturedPic2.jpg" alt="Cakes and Desserts: My DIY wedding cake" class="wp-post-image " /></article><article class="hero">
<a href="http://www.loveluxeblog.com/planning-a-wedding-on-a-tight-budget-advice-from-a-wedding-planner-and-tips-from-a-real-bride/"><span class="r">Planning a wedding on a tight budget: advice from a wedding planner</span></a>
<img width="660" height="440" src="/cache/uploads/2013/01/hero-image-7569-660-donated-flowers.jpg" alt="Planning a wedding on a tight budget: advice from a wedding planner" class="wp-post-image " /></article><article class="hero">
<a href="http://www.loveluxeblog.com/planning-a-wedding-in-france-introducing-the-amour-list/"><span class="r">Planning a wedding in France? Introducing The Amour List!</span></a>
<img width="660" height="352" src="/cache/uploads/2013/01/hero-image-7040-660-amour-list.jpg" alt="Planning a wedding in France? Introducing The Amour List!" class="wp-post-image " /></article><article class="hero">
<a href="http://www.loveluxeblog.com/free-printables-an-invitation-to-celebrate/"><span class="r">Free Printables: An Invitation to Celebrate!</span></a>
<img width="660" height="880" src="/cache/uploads/2013/01/hero-image-7396-660-Printable-Party-Invitation-Delectable-Ink-LoveLuxeBlog.jpg" alt="Free Printables: An Invitation to Celebrate!" class="wp-post-image " /></article><article class="hero">
<a href="http://www.loveluxeblog.com/winter-white-wedding-style/"><span class="r">Winter White Wedding Style</span></a>
<img width="660" height="381" src="/cache/uploads/2013/01/hero-image-7083-660-single-featured-7083-660-snowflake-boomark.jpg" alt="Winter White Wedding Style" class="wp-post-image " /></article></div></div><script type="text/javascript">/*<![CDATA[*/$(document).ready(function() {$('.home-heros').cycle({fx:'fade',prev:'#hero-prev',next:'#hero-next'});}).find('.hero').css({cursor:'pointer'}).click(function() {window.location = $(this).find('a').eq(0).prop('href');});/*]]>*/</script><div class="fl">    <div class="two-col">
<h2 class="section-title"><span>Styling and Decor</span><span class="stripe"></span></h2>
<div class="wide-wrap">
<article><div class="spacer"></div><a href="http://www.loveluxeblog.com/winter-white-wedding-style/" class="stack-a"><img width="298" height="172" src="/cache/uploads/2013/01/two-col-post-7083-298-single-featured-7083-660-snowflake-boomark.jpg" alt="Winter White Wedding Style" class="wp-post-image " /></a>    
<h4><a href="http://www.loveluxeblog.com/winter-white-wedding-style/">Winter White Wedding Style</a></h4>
<p class="meta"><strong>Posted on: </strong><a href="http://www.loveluxeblog.com/winter-white-wedding-style/"><time class="date" datetime="2013-01-12">Jan. 12th, 2013</time></a></p>
<div class="meta meta-excerpt">  There is something very magical about a winter wedding…the cool crisp air and the snowy backdrop followed by the cosy indoor celebration. My favourite style has to be a pure white affair with plenty of sparkle.

&nbsp;

Twinkly fairy lights add a lovely warmth to an all-white theme. By using</div>
<a href="http://www.loveluxeblog.com/winter-white-wedding-style/" class="meta meta-readmore">read more</a></article><div class="post-stack"><article><a href="http://www.loveluxeblog.com/happy-new-year/" class="stack-img"><img width="50" height="50" src="/cache/uploads/2012/12/small-thumb-7065-50-FrancesTaylorPhotography_Kirsten06-e1359672845390.jpg" alt="Happy New Year!" class="wp-post-image s-tmb" /></a>        <div class="stack-meta">

<h4><a href="http://www.loveluxeblog.com/happy-new-year/">Happy New Year!</a></h4>
<p class="meta"><strong>Posted on: </strong><a href="http://www.loveluxeblog.com/happy-new-year/"><time class="date" datetime="2013-01-04">Jan. 4th, 2013</time></a></p>
</div>
</article><article><a href="http://www.loveluxeblog.com/christmas-styled-shoot-little-wedding-helper/" class="stack-img"><img width="50" height="50" src="/cache/uploads/2012/12/small-thumb-6964-50-1.jpg" alt="Christmas Styled Shoot &#8211; Little Wedding Helper" class="wp-post-image s-tmb" /></a>        <div class="stack-meta">

<h4><a href="http://www.loveluxeblog.com/christmas-styled-shoot-little-wedding-helper/">Christmas Styled Shoot &#8211; Little Wedding Helper</a></h4>
<p class="meta"><strong>Posted on: </strong><a href="http://www.loveluxeblog.com/christmas-styled-shoot-little-wedding-helper/"><time class="date" datetime="2012-12-17">Dec. 17th, 2012</time></a></p>
</div>
</article><article><a href="http://www.loveluxeblog.com/jolly-festive-fun-christmas-parties-for-children/" class="stack-img"><img width="50" height="50" src="/cache/uploads/2012/11/small-thumb-5621-50-santa-placecard.jpg" alt="Jolly Festive Fun &#8211; Christmas Parties for Children" class="wp-post-image s-tmb" /></a>        <div class="stack-meta">

<h4><a href="http://www.loveluxeblog.com/jolly-festive-fun-christmas-parties-for-children/">Jolly Festive Fun &#8211; Christmas Parties for Children</a></h4>
<p class="meta"><strong>Posted on: </strong><a href="http://www.loveluxeblog.com/jolly-festive-fun-christmas-parties-for-children/"><time class="date" datetime="2012-12-10">Dec. 10th, 2012</time></a></p>
</div>
</article><article><a href="http://www.loveluxeblog.com/christmas-styled-shoot/" class="stack-img"><img width="50" height="50" src="/cache/uploads/2012/11/small-thumb-6627-50-SBPR-Xmas-Cakes-shoot-Low-res-38-of-57.jpg" alt="Christmas Styled Shoot at White Orchid Living, Surrey" class="wp-post-image s-tmb" /></a>        <div class="stack-meta">

<h4><a href="http://www.loveluxeblog.com/christmas-styled-shoot/">Christmas Styled Shoot at White Orchid Living, Surrey</a></h4>
<p class="meta"><strong>Posted on: </strong><a href="http://www.loveluxeblog.com/christmas-styled-shoot/"><time class="date" datetime="2012-11-30">Nov. 30th, 2012</time></a></p>
</div>
</article></div><nav class="home-pagination pagination"><a href="/category/styling-and-decor">See all posts »</a></nav></div></div>    <div class="two-col even">
<h2 class="section-title"><span>Real Life Inspiration</span><span class="stripe"></span></h2>
<div class="wide-wrap">
<article><div class="spacer"></div><a href="http://www.loveluxeblog.com/gorgeous-rustic-baby-shower/" class="stack-a"><img width="298" height="199" src="/cache/uploads/2012/12/two-col-post-6997-298-Helens-Baby-Shower-9-of-34.jpg" alt="Gorgeous Rustic Baby Shower" class="wp-post-image " /></a>    
<h4><a href="http://www.loveluxeblog.com/gorgeous-rustic-baby-shower/">Gorgeous Rustic Baby Shower</a></h4>
<p class="meta"><strong>Posted on: </strong><a href="http://www.loveluxeblog.com/gorgeous-rustic-baby-shower/"><time class="date" datetime="2012-12-19">Dec. 19th, 2012</time></a></p>
<div class="meta meta-excerpt">  Hope everyone is well and excited about Christmas with less than a week to go - eeeek! This will be my first year cooking for the family so as I've never even done so much as a roast before we shall have to see how that goes!! :)

&nbsp;

Today I'm sharing this beau-ti-ful vintage and rustic</div>
<a href="http://www.loveluxeblog.com/gorgeous-rustic-baby-shower/" class="meta meta-readmore">read more</a></article><div class="post-stack"><article><a href="http://www.loveluxeblog.com/real-weddings-a-tale-of-three-wedding-dresses/" class="stack-img"><img width="50" height="50" src="/cache/uploads/2012/12/small-thumb-6762-50-uk-wedding-blog-loveluxe-205.jpg" alt="Real Weddings: A Tale of Three Wedding Dresses" class="wp-post-image s-tmb" /></a>        <div class="stack-meta">

<h4><a href="http://www.loveluxeblog.com/real-weddings-a-tale-of-three-wedding-dresses/">Real Weddings: A Tale of Three Wedding Dresses</a></h4>
<p class="meta"><strong>Posted on: </strong><a href="http://www.loveluxeblog.com/real-weddings-a-tale-of-three-wedding-dresses/"><time class="date" datetime="2012-12-05">Dec. 5th, 2012</time></a></p>
</div>
</article><article><a href="http://www.loveluxeblog.com/parties-golden-apple-turns-one/" class="stack-img"><img width="50" height="50" src="/cache/uploads/2012/12/small-thumb-6713-50-leah-golden-apple-designs-010.jpg" alt="Parties: Golden Apple Turns One!" class="wp-post-image s-tmb" /></a>        <div class="stack-meta">

<h4><a href="http://www.loveluxeblog.com/parties-golden-apple-turns-one/">Parties: Golden Apple Turns One!</a></h4>
<p class="meta"><strong>Posted on: </strong><a href="http://www.loveluxeblog.com/parties-golden-apple-turns-one/"><time class="date" datetime="2012-12-03">Dec. 3rd, 2012</time></a></p>
</div>
</article><article><a href="http://www.loveluxeblog.com/launch-parties-oh-my-party-with-louise-from-oh-my-honey-the-funfair-club-brighton/" class="stack-img"><img width="50" height="50" src="/cache/uploads/2012/11/small-thumb-6217-50-oh-my-honey-dress-launch-1033.jpg" alt="Oh My Party &#8211; The Funfair Club, Brighton" class="wp-post-image s-tmb" /></a>        <div class="stack-meta">

<h4><a href="http://www.loveluxeblog.com/launch-parties-oh-my-party-with-louise-from-oh-my-honey-the-funfair-club-brighton/">Oh My Party &#8211; The Funfair Club, Brighton</a></h4>
<p class="meta"><strong>Posted on: </strong><a href="http://www.loveluxeblog.com/launch-parties-oh-my-party-with-louise-from-oh-my-honey-the-funfair-club-brighton/"><time class="date" datetime="2012-11-23">Nov. 23rd, 2012</time></a></p>
</div>
</article><article><a href="http://www.loveluxeblog.com/parties-monochrome-baby-shower/" class="stack-img"><img width="50" height="50" src="/cache/uploads/2012/11/small-thumb-5538-50-milk-themed-baby-shower1.jpg" alt="Parties : Monochrome Baby Shower" class="wp-post-image s-tmb" /></a>        <div class="stack-meta">

<h4><a href="http://www.loveluxeblog.com/parties-monochrome-baby-shower/">Parties : Monochrome Baby Shower</a></h4>
<p class="meta"><strong>Posted on: </strong><a href="http://www.loveluxeblog.com/parties-monochrome-baby-shower/"><time class="date" datetime="2012-11-15">Nov. 15th, 2012</time></a></p>
</div>
</article></div><nav class="home-pagination pagination"><a href="/category/real-life-inspiration">See all posts »</a></nav></div></div></div><div class="wide-section">
<h2 class="section-title"><span>Latest Video</span><span class="stripe"></span></h2>
<div class="wide-wrap tc">
<iframe width="658" height="369" style="margin:auto;border:0;" src="http://www.youtube-nocookie.com/embed/videoseries?list=UUt2hkAdH-yzARfjn4BCWUog"></iframe>
</div>
</div><div class="fl">    <div class="two-col">
<h2 class="section-title"><span>Family and Relationships</span><span class="stripe"></span></h2>
<div class="wide-wrap">
<article><div class="spacer"></div><a href="http://www.loveluxeblog.com/missing-family-members-on-your-wedding-day-finding-happiness/" class="stack-a"><img width="298" height="198" src="/cache/uploads/2013/01/two-col-post-7352-298-MG_8932-e1359671935381.jpg" alt="Missing family members on your wedding day: finding happiness" class="wp-post-image " /></a>    
<h4><a href="http://www.loveluxeblog.com/missing-family-members-on-your-wedding-day-finding-happiness/">Missing family members on your wedding day: finding happiness</a></h4>
<p class="meta"><strong>Posted on: </strong><a href="http://www.loveluxeblog.com/missing-family-members-on-your-wedding-day-finding-happiness/"><time class="date" datetime="2013-01-07">Jan. 7th, 2013</time></a></p>
<div class="meta meta-excerpt">  Happy 2013 everyone! My name is Jessie and I'm a wedding planner &amp; stylist based in the Cotswolds. I'm a regular guest blogger here on LoveLuxe but also have my own little blog where you can read my musings about life and work in Gloucestershire!

&nbsp;

To kick off the new year I decided</div>
<a href="http://www.loveluxeblog.com/missing-family-members-on-your-wedding-day-finding-happiness/" class="meta meta-readmore">read more</a></article><div class="post-stack"><article><a href="http://www.loveluxeblog.com/reframing-the-art-gallery-for-children/" class="stack-img"><img width="50" height="50" src="/cache/uploads/2012/11/small-thumb-6365-50-gallery09.jpg" alt="Reframing the Art Gallery for Children." class="wp-post-image s-tmb" /></a>        <div class="stack-meta">

<h4><a href="http://www.loveluxeblog.com/reframing-the-art-gallery-for-children/">Reframing the Art Gallery for Children.</a></h4>
<p class="meta"><strong>Posted on: </strong><a href="http://www.loveluxeblog.com/reframing-the-art-gallery-for-children/"><time class="date" datetime="2012-11-27">Nov. 27th, 2012</time></a></p>
</div>
</article><article><a href="http://www.loveluxeblog.com/love-the-second-time-around-a-second-marriage/" class="stack-img"><img width="50" height="50" src="/cache/uploads/2012/11/small-thumb-5203-50-second-marriage-by-becky-male-photography.jpg" alt="Love the second time around : A Second Marriage" class="wp-post-image s-tmb" /></a>        <div class="stack-meta">

<h4><a href="http://www.loveluxeblog.com/love-the-second-time-around-a-second-marriage/">Love the second time around : A Second Marriage</a></h4>
<p class="meta"><strong>Posted on: </strong><a href="http://www.loveluxeblog.com/love-the-second-time-around-a-second-marriage/"><time class="date" datetime="2012-11-07">Nov. 7th, 2012</time></a></p>
</div>
</article><article><a href="http://www.loveluxeblog.com/celebrating-halloween-5-simple-steps-to-throwing-a-spooktacular-family-movie-night/" class="stack-img"><img width="50" height="50" src="/cache/uploads/2012/10/small-thumb-4631-50-family-halloween.jpg" alt="Celebrating Halloween: 5 Simple Steps to Throwing a Spooktacular Family Movie Night!" class="wp-post-image s-tmb" /></a>        <div class="stack-meta">

<h4><a href="http://www.loveluxeblog.com/celebrating-halloween-5-simple-steps-to-throwing-a-spooktacular-family-movie-night/">Celebrating Halloween: 5 Simple Steps to Throwing a Spooktacular Family Movie Night!</a></h4>
<p class="meta"><strong>Posted on: </strong><a href="http://www.loveluxeblog.com/celebrating-halloween-5-simple-steps-to-throwing-a-spooktacular-family-movie-night/"><time class="date" datetime="2012-10-28">Oct. 28th, 2012</time></a></p>
</div>
</article></div><nav class="home-pagination pagination"><a href="/category/family-and-relationships">See all posts »</a></nav></div></div>    <div class="two-col even">
<h2 class="section-title"><span>Planning Tips and Advice</span><span class="stripe"></span></h2>
<div class="wide-wrap">
<article><div class="spacer"></div><a href="http://www.loveluxeblog.com/cakes-and-desserts-my-diy-wedding-cake/" class="stack-a"><img width="298" height="132" src="/cache/uploads/2013/02/two-col-post-7753-298-LoveLuxe-Post01-BB-FeaturedPic2.jpg" alt="Cakes and Desserts: My DIY wedding cake" class="wp-post-image " /></a>    
<h4><a href="http://www.loveluxeblog.com/cakes-and-desserts-my-diy-wedding-cake/">Cakes and Desserts: My DIY wedding cake</a></h4>
<p class="meta"><strong>Posted on: </strong><a href="http://www.loveluxeblog.com/cakes-and-desserts-my-diy-wedding-cake/"><time class="date" datetime="2013-02-02">Feb. 2nd, 2013</time></a></p>
<div class="meta meta-excerpt">  Hello! My name is Laura, I run a small bakery business down here in sunny Bristol, and I’m here to talk to you about all things cake! As I was wondering how to introduce myself to you, I came upon the idea that the perfect way would be to talk to you about a cake of my own. In fact, my very own</div>
<a href="http://www.loveluxeblog.com/cakes-and-desserts-my-diy-wedding-cake/" class="meta meta-readmore">read more</a></article><div class="post-stack"><article><a href="http://www.loveluxeblog.com/planning-a-wedding-on-a-tight-budget-advice-from-a-wedding-planner-and-tips-from-a-real-bride/" class="stack-img"><img width="50" height="50" src="/cache/uploads/2013/01/small-thumb-7569-50-donated-flowers.jpg" alt="Planning a wedding on a tight budget: advice from a wedding planner" class="wp-post-image s-tmb" /></a>        <div class="stack-meta">

<h4><a href="http://www.loveluxeblog.com/planning-a-wedding-on-a-tight-budget-advice-from-a-wedding-planner-and-tips-from-a-real-bride/">Planning a wedding on a tight budget: advice from a wedding planner</a></h4>
<p class="meta"><strong>Posted on: </strong><a href="http://www.loveluxeblog.com/planning-a-wedding-on-a-tight-budget-advice-from-a-wedding-planner-and-tips-from-a-real-bride/"><time class="date" datetime="2013-01-31">Jan. 31st, 2013</time></a></p>
</div>
</article><article><a href="http://www.loveluxeblog.com/free-printables-an-invitation-to-celebrate/" class="stack-img"><img width="50" height="50" src="/cache/uploads/2013/01/small-thumb-7396-50-Printable-Party-Invitation-Delectable-Ink-LoveLuxeBlog.jpg" alt="Free Printables: An Invitation to Celebrate!" class="wp-post-image s-tmb" /></a>        <div class="stack-meta">

<h4><a href="http://www.loveluxeblog.com/free-printables-an-invitation-to-celebrate/">Free Printables: An Invitation to Celebrate!</a></h4>
<p class="meta"><strong>Posted on: </strong><a href="http://www.loveluxeblog.com/free-printables-an-invitation-to-celebrate/"><time class="date" datetime="2013-01-17">Jan. 17th, 2013</time></a></p>
</div>
</article><article><a href="http://www.loveluxeblog.com/how-to-plan-a-childrens-birthday-party/" class="stack-img"><img width="50" height="50" src="/cache/uploads/2012/11/small-thumb-6394-50-Russian-Dolls-Party-Invitations-for-Girls-front-and-reverse.jpg" alt="How to plan a children’s birthday party" class="wp-post-image s-tmb" /></a>        <div class="stack-meta">

<h4><a href="http://www.loveluxeblog.com/how-to-plan-a-childrens-birthday-party/">How to plan a children’s birthday party</a></h4>
<p class="meta"><strong>Posted on: </strong><a href="http://www.loveluxeblog.com/how-to-plan-a-childrens-birthday-party/"><time class="date" datetime="2012-12-05">Dec. 5th, 2012</time></a></p>
</div>
</article><article><a href="http://www.loveluxeblog.com/are-you-lost-for-words-wedding-invitation-etiquette/" class="stack-img"><img width="50" height="50" src="/cache/uploads/2012/11/small-thumb-6127-50-from-couple.jpg" alt="Lost for Words? Wedding Invitation Etiquette" class="wp-post-image s-tmb" /></a>        <div class="stack-meta">

<h4><a href="http://www.loveluxeblog.com/are-you-lost-for-words-wedding-invitation-etiquette/">Lost for Words? Wedding Invitation Etiquette</a></h4>
<p class="meta"><strong>Posted on: </strong><a href="http://www.loveluxeblog.com/are-you-lost-for-words-wedding-invitation-etiquette/"><time class="date" datetime="2012-11-24">Nov. 24th, 2012</time></a></p>
</div>
</article></div><nav class="home-pagination pagination"><a href="/category/planning-tips-and-advice">See all posts »</a></nav></div></div></div><div class="wide-section one-col">                <h2 class="section-title"><span>Beauty and Fashion</span><span class="stripe"></span></h2>
<div class="wide-wrap">
<article><div class="header fl"><a href="http://www.loveluxeblog.com/fashion-steal-their-style-christmas-parties/" class="headimg fl"><img width="300" height="254" src="/cache/uploads/2012/11/one-col-post-6513-300-taylorswift.jpg" alt="Fashion : Steal Their Style &#8211; Christmas Parties" class="wp-post-image " /></a>                <div class="fl">
<h4 class="fl"><a href="http://www.loveluxeblog.com/fashion-steal-their-style-christmas-parties/">Fashion : Steal Their Style &#8211; Christmas Parties</a></h4>
<p class="meta fl"><strong>Posted on: </strong><a href="http://www.loveluxeblog.com/fashion-steal-their-style-christmas-parties/"><time class="date" datetime="2012-12-04">Dec. 4th, 2012</time></a></p>
<div class="meta meta-excerpt">  Hi everyone – for this month’s post I couldn’t be more excited to be bringing you some fashion ideas to see you through the festive party season. I literally have to be restrained from October September onwards from diving headlong into Christmas prematurely, so now that it’s actually</div>
<a href="http://www.loveluxeblog.com/fashion-steal-their-style-christmas-parties/" class="meta meta-readmore">read more</a>                </div></div>            </article>
<div class="post-stack">

<article><a href="http://www.loveluxeblog.com/a-pair-of-detachable-shoe-bows/" class="stack-img"><img width="50" height="50" src="/cache/uploads/2012/11/small-thumb-4961-50-diy-shoe-bow-tutorial.jpg" alt="a pair of detachable shoe bows" class="wp-post-image s-tmb" /></a>                <div class="stack-meta">
<h4><a href="http://www.loveluxeblog.com/a-pair-of-detachable-shoe-bows/">a pair of detachable shoe bows</a></h4>
<p class="meta"><strong>Posted on: </strong><a href="http://www.loveluxeblog.com/a-pair-of-detachable-shoe-bows/"><time class="date" datetime="2012-11-04">Nov. 4th, 2012</time></a></p>
</div>
</article>
<article><a href="http://www.loveluxeblog.com/fashion-steal-her-style-blake-lively/" class="stack-img"><img width="50" height="50" src="/cache/uploads/2012/11/small-thumb-4786-50-blake-lively.jpg" alt="Fashion : Steal Her Style &#8211; Blake Lively" class="wp-post-image s-tmb" /></a>                <div class="stack-meta">
<h4><a href="http://www.loveluxeblog.com/fashion-steal-her-style-blake-lively/">Fashion : Steal Her Style &#8211; Blake Lively</a></h4>
<p class="meta"><strong>Posted on: </strong><a href="http://www.loveluxeblog.com/fashion-steal-her-style-blake-lively/"><time class="date" datetime="2012-11-02">Nov. 2nd, 2012</time></a></p>
</div>
</article>
<article><a href="http://www.loveluxeblog.com/style-trends-how-to-create-the-perfect-ponytail/" class="stack-img"><img width="50" height="50" src="/cache/uploads/2012/08/small-thumb-3789-50-how-to-create-wedding-ponytail.jpg" alt="How to create the Perfect Ponytail" class="wp-post-image s-tmb" /></a>                <div class="stack-meta">
<h4><a href="http://www.loveluxeblog.com/style-trends-how-to-create-the-perfect-ponytail/">How to create the Perfect Ponytail</a></h4>
<p class="meta"><strong>Posted on: </strong><a href="http://www.loveluxeblog.com/style-trends-how-to-create-the-perfect-ponytail/"><time class="date" datetime="2012-08-15">Aug. 15th, 2012</time></a></p>
</div>
</article>
<article><a href="http://www.loveluxeblog.com/style-trends-the-natural-wedding-makeup-look/" class="stack-img"><img width="50" height="50" src="/cache/uploads/2012/07/small-thumb-2295-50-natural-wedding-makeup-tips.jpg" alt="The Natural Wedding Makeup Look" class="wp-post-image s-tmb" /></a>                <div class="stack-meta">
<h4><a href="http://www.loveluxeblog.com/style-trends-the-natural-wedding-makeup-look/">The Natural Wedding Makeup Look</a></h4>
<p class="meta"><strong>Posted on: </strong><a href="http://www.loveluxeblog.com/style-trends-the-natural-wedding-makeup-look/"><time class="date" datetime="2012-07-04">Jul. 4th, 2012</time></a></p>
</div>
</article>
</div><nav class="home-pagination pagination"><a href="/category/beauty-and-fashion">See all posts »</a></nav></div></div><div class="fl">    <div class="two-col">
<h2 class="section-title"><span>Travel</span><span class="stripe"></span></h2>
<div class="wide-wrap">
<article><div class="spacer"></div><a href="http://www.loveluxeblog.com/planning-a-wedding-in-france-introducing-the-amour-list/" class="stack-a"><img width="298" height="158" src="/cache/uploads/2013/01/two-col-post-7040-298-amour-list.jpg" alt="Planning a wedding in France? Introducing The Amour List!" class="wp-post-image " /></a>    
<h4><a href="http://www.loveluxeblog.com/planning-a-wedding-in-france-introducing-the-amour-list/">Planning a wedding in France? Introducing The Amour List!</a></h4>
<p class="meta"><strong>Posted on: </strong><a href="http://www.loveluxeblog.com/planning-a-wedding-in-france-introducing-the-amour-list/"><time class="date" datetime="2013-01-28">Jan. 28th, 2013</time></a></p>
<div class="meta meta-excerpt">  I am thrilled, excited and a little nervous to introduce to you French Wedding Style's latest project The Amour List - wedding book France!  The Amour List is the first destination wedding directory in English solely dedicated to France, and it is the direct result of brides’ feedback about the</div>
<a href="http://www.loveluxeblog.com/planning-a-wedding-in-france-introducing-the-amour-list/" class="meta meta-readmore">read more</a></article><div class="post-stack"><article><a href="http://www.loveluxeblog.com/winter-weddings-in-france/" class="stack-img"><img width="50" height="50" src="/cache/uploads/2012/12/small-thumb-6673-50-grangesdenhautchamonix.jpg" alt="Winter Weddings in France" class="wp-post-image s-tmb" /></a>        <div class="stack-meta">

<h4><a href="http://www.loveluxeblog.com/winter-weddings-in-france/">Winter Weddings in France</a></h4>
<p class="meta"><strong>Posted on: </strong><a href="http://www.loveluxeblog.com/winter-weddings-in-france/"><time class="date" datetime="2012-12-06">Dec. 6th, 2012</time></a></p>
</div>
</article><article><a href="http://www.loveluxeblog.com/weddings-france-queen-of-your-own-wedding-chateau-monique-french-wedding-style/" class="stack-img"><img width="50" height="50" src="/cache/uploads/2012/11/small-thumb-4704-50-french-chateau-wedding-venue.jpg" alt="Weddings in France: Queen of your own Wedding Chateau" class="wp-post-image s-tmb" /></a>        <div class="stack-meta">

<h4><a href="http://www.loveluxeblog.com/weddings-france-queen-of-your-own-wedding-chateau-monique-french-wedding-style/">Weddings in France: Queen of your own Wedding Chateau</a></h4>
<p class="meta"><strong>Posted on: </strong><a href="http://www.loveluxeblog.com/weddings-france-queen-of-your-own-wedding-chateau-monique-french-wedding-style/"><time class="date" datetime="2012-11-03">Nov. 3rd, 2012</time></a></p>
</div>
</article><article><a href="http://www.loveluxeblog.com/style-trends-getting-married-in-france-by-monique-french-wedding-style/" class="stack-img"><img width="50" height="50" src="/cache/uploads/2012/09/small-thumb-4275-50-married-france-wedding.jpg" alt="Getting Married in France" class="wp-post-image s-tmb" /></a>        <div class="stack-meta">

<h4><a href="http://www.loveluxeblog.com/style-trends-getting-married-in-france-by-monique-french-wedding-style/">Getting Married in France</a></h4>
<p class="meta"><strong>Posted on: </strong><a href="http://www.loveluxeblog.com/style-trends-getting-married-in-france-by-monique-french-wedding-style/"><time class="date" datetime="2012-09-20">Sep. 20th, 2012</time></a></p>
</div>
</article><article><a href="http://www.loveluxeblog.com/styled-shoots-a-paris-wedding-shoot/" class="stack-img"><img width="50" height="50" src="/cache/uploads/2012/06/small-thumb-1818-50-paris-wedding-shoot.jpg" alt="Styled Shoots : A Paris Wedding Shoot" class="wp-post-image s-tmb" /></a>        <div class="stack-meta">

<h4><a href="http://www.loveluxeblog.com/styled-shoots-a-paris-wedding-shoot/">Styled Shoots : A Paris Wedding Shoot</a></h4>
<p class="meta"><strong>Posted on: </strong><a href="http://www.loveluxeblog.com/styled-shoots-a-paris-wedding-shoot/"><time class="date" datetime="2012-06-18">Jun. 18th, 2012</time></a></p>
</div>
</article></div><nav class="home-pagination pagination"><a href="/category/travel">See all posts »</a></nav></div></div>    <div class="two-col even">
<h2 class="section-title"><span>Events, Hangouts and Video Q&amp;As</span><span class="stripe"></span></h2>
<div class="wide-wrap">
<article><div class="spacer"></div><a href="http://www.loveluxeblog.com/loveluxe-hangouts-making-christmas-special-for-children/" class="stack-a"><img width="298" height="195" src="/cache/uploads/2012/12/two-col-post-6883-298-hangout-christmas.jpg" alt="LoveLuxe Hangouts: Making Christmas Special for Children" class="wp-post-image " /></a>    
<h4><a href="http://www.loveluxeblog.com/loveluxe-hangouts-making-christmas-special-for-children/">LoveLuxe Hangouts: Making Christmas Special for Children</a></h4>
<p class="meta"><strong>Posted on: </strong><a href="http://www.loveluxeblog.com/loveluxe-hangouts-making-christmas-special-for-children/"><time class="date" datetime="2012-12-05">Dec. 5th, 2012</time></a></p>
<div class="meta meta-excerpt">  Hope you've had a great fortnight since our last LoveLuxe Hangout!   Tonight we're going to be talking on the topic of Making Christmas Special for Children (our hashtag tonight to join in the conversation is #loveluxechristmas). From ideas on how to cultivate new family traditions to how to keep</div>
                                                                                                                                                                                               <a href="http://www.loveluxeblog.com/loveluxe-hangouts-making-christmas-special-for-children/" class="meta meta-readmore">read more</a></article><div class="post-stack"><article><a href="http://www.loveluxeblog.com/launch-parties-oh-my-party-with-louise-from-oh-my-honey-the-funfair-club-brighton/" class="stack-img"><img width="50" height="50" src="/cache/uploads/2012/11/small-thumb-6217-50-oh-my-honey-dress-launch-1033.jpg" alt="Oh My Party &#8211; The Funfair Club, Brighton" class="wp-post-image s-tmb" /></a>        <div class="stack-meta">
                                                                                                                                                                                               
                                                                                                                                                                                               <h4><a href="http://www.loveluxeblog.com/launch-parties-oh-my-party-with-louise-from-oh-my-honey-the-funfair-club-brighton/">Oh My Party &#8211; The Funfair Club, Brighton</a></h4>
                                                                                                                                                                                               <p class="meta"><strong>Posted on: </strong><a href="http://www.loveluxeblog.com/launch-parties-oh-my-party-with-louise-from-oh-my-honey-the-funfair-club-brighton/"><time class="date" datetime="2012-11-23">Nov. 23rd, 2012</time></a></p>
                                                                                                                                                                                               </div>
                                                                                                                                                                                               </article><article><a href="http://www.loveluxeblog.com/loveluxe-hangouts-christmas-open-house-party/" class="stack-img"><img width="50" height="50" src="/cache/uploads/2012/11/small-thumb-6103-50-christmas-open-house-header.jpg" alt="LoveLuxe Hangouts : Christmas Open House Party" class="wp-post-image s-tmb" /></a>        <div class="stack-meta">
                                                                                                                                                                                               
                                                                                                                                                                                               <h4><a href="http://www.loveluxeblog.com/loveluxe-hangouts-christmas-open-house-party/">LoveLuxe Hangouts : Christmas Open House Party</a></h4>
                                                                                                                                                                                               <p class="meta"><strong>Posted on: </strong><a href="http://www.loveluxeblog.com/loveluxe-hangouts-christmas-open-house-party/"><time class="date" datetime="2012-11-21">Nov. 21st, 2012</time></a></p>
                                                                                                                                                                                               </div>
                                                                                                                                                                                               </article><article><a href="http://www.loveluxeblog.com/johanna-hehir-white-rose-bridal-boutique-event-coverage-from-the-cotswolds-house-hotel/" class="stack-img"><img width="50" height="50" src="/cache/uploads/2012/11/small-thumb-5759-50-johanna-hehir-cotswolds.jpg" alt="Johanna Hehir + White Rose Bridal Boutique Showcase" class="wp-post-image s-tmb" /></a>        <div class="stack-meta">
                                                                                                                                                                                               
                                                                                                                                                                                               <h4><a href="http://www.loveluxeblog.com/johanna-hehir-white-rose-bridal-boutique-event-coverage-from-the-cotswolds-house-hotel/">Johanna Hehir + White Rose Bridal Boutique Showcase</a></h4>
                                                                                                                                                                                               <p class="meta"><strong>Posted on: </strong><a href="http://www.loveluxeblog.com/johanna-hehir-white-rose-bridal-boutique-event-coverage-from-the-cotswolds-house-hotel/"><time class="date" datetime="2012-11-10">Nov. 10th, 2012</time></a></p>
                                                                                                                                                                                               </div>
                                                                                                                                                                                               </article><article><a href="http://www.loveluxeblog.com/hermione-harbutt-launch-party-clifton-bristol/" class="stack-img"><img width="50" height="50" src="/cache/uploads/2012/11/small-thumb-5694-50-hermione-harbutt-launch-party.jpg" alt="Hermione Harbutt Launch Party : Clifton, Bristol" class="wp-post-image s-tmb" /></a>        <div class="stack-meta">
                                                                                                                                                                                               
                                                                                                                                                                                               <h4><a href="http://www.loveluxeblog.com/hermione-harbutt-launch-party-clifton-bristol/">Hermione Harbutt Launch Party : Clifton, Bristol</a></h4>
                                                                                                                                                                                               <p class="meta"><strong>Posted on: </strong><a href="http://www.loveluxeblog.com/hermione-harbutt-launch-party-clifton-bristol/"><time class="date" datetime="2012-11-09">Nov. 9th, 2012</time></a></p>
                                                                                                                                                                                               </div>
                                                                                                                                                                                               </article></div><nav class="home-pagination pagination"><a href="/category/events-hangouts-and-video-qas">See all posts »</a></nav></div></div></div></div><div class="content-right"><section class="col2">
                                                                                                                                                                                               <div class="sidebar-wrap">
                                                                                                                                                                                               <a href="http://www.lightboxstudios.co.uk" style="float: left; width: 100%; height: auto;"><img alt="Lightbox Digital Studios" style="float: left; width: 100%; height: auto;" src="/adverts_temp_store/a4ff2bab6b744eab1313146676f39e9f/ant.jpg"></a></div><div class="sidebar-wrap large-button"><aside class="widget widget_sp_image"><a href="/advertise/"><img src="/images/advertise.jpg" alt="advertise" /></a></aside></div><div class="sidebar-wrap">
                                                                                                                                                                                               
                                                                                                                                                                                               <aside class="widget widget_sp_image">
                                                                                                                                                                                               
                                                                                                                                                                                               <a target="_blank" href="http://www.rebeccalancasterdesigns.com" onclick="_gaq.push(['_trackEvent', 'Sidebar Advert', 'Click', 'Rebecca Lancaster Designs']);" class="widget_sp_image-image-link "><img alt="" class="aligncenter" width="200" src="http://www.loveluxeblog.com//adverts_temp_store/3d038ff3f5cd6515b93a559dc0382402/1359483857_ll%20logo.jpg"></a>
                                                                                                                                                                                               <a target="_blank" href="http://www.devonvintagechina.co.uk/" onclick="_gaq.push(['_trackEvent', 'Sidebar Advert', 'Click', 'Devon Vintage China']);" class="widget_sp_image-image-link "><img alt="" class="aligncenter" width="200" src="http://www.loveluxeblog.com//adverts_temp_store/bd0678383f5a894d22fbea0c195c2da7/1344455787_love%20luxe%20ad%201.jpg"></a>
                                                                                                                                                                                               <a target="_blank" href="http://www.flowersbyfleuri.com" onclick="_gaq.push(['_trackEvent', 'Sidebar Advert', 'Click', 'Flowers by Fleuri']);" class="widget_sp_image-image-link "><img alt="" class="aligncenter" width="200" src="http://www.loveluxeblog.com//adverts_temp_store/f4f02c5d1b7f7f42c6898c2d359afce9/1352464914_fleuri_logo174x90%20copy%202.jpg"></a>
                                                                                                                                                                                               <a target="_blank" href="http://www.beckymalephotography.com" onclick="_gaq.push(['_trackEvent', 'Sidebar Advert', 'Click', 'Becky Male Photography']);" class="widget_sp_image-image-link "><img alt="" class="aligncenter" width="200" src="http://www.loveluxeblog.com//adverts_temp_store/3af2ee5450a1b8f64aa5d1f10127352d/1345661241_-2.jpg"></a>
                                                                                                                                                                                               <a target="_blank" href="http://www.carternendick.com" onclick="_gaq.push(['_trackEvent', 'Sidebar Advert', 'Click', 'Carter Nendick Weddings and Events ']);" class="widget_sp_image-image-link no-mg-bottom"><img alt="" class="aligncenter" width="200" src="http://www.loveluxeblog.com//adverts_temp_store/97800606aa8f79527d1e69cb161104af/1359020350_Carter%20Nendick_Love%20Luxe.jpg"></a>
                                                                                                                                                                                               <a target="_blank" href="http://www.naomikenton.co.uk" onclick="_gaq.push(['_trackEvent', 'Sidebar Advert', 'Click', 'Naomi Kenton Photography']);" class="widget_sp_image-image-link no-mg-bottom"><img alt="" class="aligncenter" width="200" src="http://www.loveluxeblog.com//adverts_temp_store/951c4fc0adbe7302792a34953f309757/1348659922_naomi-banner-ad-loveluxe.jpg"></a>            </aside>
                                                                                                                                                                                               </div>
                                                                                                                                                                                               <div class="sidebar-wrap">
                                                                                                                                                                                               <iframe src="//www.facebook.com/plugins/likebox.php?href=http%3A%2F%2Fwww.facebook.com%2Floveluxeblog&amp;width=410&amp;height=325&amp;show_faces=true&amp;colorscheme=light&amp;stream=false&amp;border_color=%23cccccc&amp;header=true&amp;appId=195485953818125" style="border:none; overflow:hidden; width:410px; height:325px;"></iframe>
                                                                                                                                                                                               </div>
                                                                                                                                                                                               <div class="sidebar-wrap">
                                                                                                                                                                                               <aside class="widget widget_sp_image">
                                                                                                                                                                                               
                                                                                                                                                                                               <a target="_blank" href="http://www.charlottebryer-ash.com" onclick="_gaq.push(['_trackEvent', 'Sidebar Advert', 'Click', 'Charlotte Bryer-Ash Photography']);" class="widget_sp_image-image-link "><img alt="" class="aligncenter" width="200" src="http://www.loveluxeblog.com//adverts_temp_store/1828f5c0423a9688ce7aa1e28c15c7d2/1353105433_Charlotte%20Bryer-Ash%20Photography%20Advert.jpg"></a>
                                                                                                                                                                                               <a target="_blank" href="http://www.charliescribble.com" onclick="_gaq.push(['_trackEvent', 'Sidebar Advert', 'Click', 'Charlie Scribble']);" class="widget_sp_image-image-link "><img alt="" class="aligncenter" width="200" src="http://www.loveluxeblog.com//adverts_temp_store/1417277de869c8a218071c0ff354a3a6/1349099352_Charlie%20Scribble.jpg"></a>
                                                                                                                                                                                               <a target="_blank" href="http://www.myfabulouslife.co.uk" onclick="_gaq.push(['_trackEvent', 'Sidebar Advert', 'Click', 'My Fabuous LIfe Photography ']);" class="widget_sp_image-image-link "><img alt="" class="aligncenter" width="200" src="http://www.loveluxeblog.com//adverts_temp_store/3ae681cf0190ddbdc18b39ff13b2da48/1346230817_LoveLuxeAd.jpg"></a>
                                                                                                                                                                                               <a target="_blank" href="http://www.annelimarinovich.com" onclick="_gaq.push(['_trackEvent', 'Sidebar Advert', 'Click', 'Anneli Marinovich Photography']);" class="widget_sp_image-image-link "><img alt="" class="aligncenter" width="200" src="http://www.loveluxeblog.com//adverts_temp_store/9598a9c61a41661bf40f95518f87ac11/1359369792_Love%20Luxe%20Banner%20Feb%2013%20Anneli%20Marinovich%20Photography.jpg"></a>
                                                                                                                                                                                               <a target="_blank" href="http://www.bespoketiarasbysarahroberts.co.uk" onclick="_gaq.push(['_trackEvent', 'Sidebar Advert', 'Click', 'Bespoke Tiaras by Sarah Roberts']);" class="widget_sp_image-image-link "><img alt="" class="aligncenter" width="200" src="http://www.loveluxeblog.com//adverts_temp_store/7fa479107232532c9a8007a9499cf656/1359300987_banner-new-90by200.png"></a>
                                                                                                                                                                                               <a target="_blank" href="http://www.dhwphotography.co.uk" onclick="_gaq.push(['_trackEvent', 'Sidebar Advert', 'Click', 'Daniel Weeks']);" class="widget_sp_image-image-link "><img alt="" class="aligncenter" width="200" src="http://www.loveluxeblog.com//adverts_temp_store/431b865b2a81c7be8451f176fc06307e/1344895467_loveluxeDHW.jpg"></a>
                                                                                                                                                                                               <a target="_blank" href="http://www.rosetintmywedding.co.uk" onclick="_gaq.push(['_trackEvent', 'Sidebar Advert', 'Click', 'Rose Tint My Wedding']);" class="widget_sp_image-image-link "><img alt="" class="aligncenter" width="200" src="http://www.loveluxeblog.com//adverts_temp_store/d0f756901d260192982ca99fad38a0d3/1354546778_Banner%20ad%203%20for%20Love%20Luxe%20Blog.png"></a>
                                                                                                                                                                                               <a target="_blank" href="http://www.victoriaphippsphotography.co.uk" onclick="_gaq.push(['_trackEvent', 'Sidebar Advert', 'Click', 'victoria phipps photography']);" class="widget_sp_image-image-link "><img alt="" class="aligncenter" width="200" src="http://www.loveluxeblog.com//adverts_temp_store/e309582d776e0edf0fbd67c65439c027/1358851552_love%20luxe%20blog%20ad.jpg"></a>
                                                                                                                                                                                               <a target="_blank" href="http://www.lauracalderwood.co.uk" onclick="_gaq.push(['_trackEvent', 'Sidebar Advert', 'Click', 'Laura Calderwood Photography']);" class="widget_sp_image-image-link "><img alt="" class="aligncenter" width="200" src="http://www.loveluxeblog.com//adverts_temp_store/5bfa047267aaf0143f4f02b5312ead2d/1358844033_loveluxead.jpg"></a>
                                                                                                                                                                                               <a target="_blank" href="http://www.thecraftybaker.co" onclick="_gaq.push(['_trackEvent', 'Sidebar Advert', 'Click', 'The Crafty Baker']);" class="widget_sp_image-image-link "><img alt="" class="aligncenter" width="200" src="http://www.loveluxeblog.com//adverts_temp_store/eda703fa1cd185f0f4610a53026f4b2d/1359754228_new%20banner3.jpg"></a>
                                                                                                                                                                                               <a target="_blank" href="http://www.samueldocker.co.uk" onclick="_gaq.push(['_trackEvent', 'Sidebar Advert', 'Click', 'Samuel Docker Photography']);" class="widget_sp_image-image-link "><img alt="" class="aligncenter" width="200" src="http://www.loveluxeblog.com//adverts_temp_store/f7b412d699fde0455ffd588bf68b6ebe/1357205643_LoveLuxe2.jpg"></a>
                                                                                                                                                                                               <a target="_blank" href="http://storry.co.uk/" onclick="_gaq.push(['_trackEvent', 'Sidebar Advert', 'Click', 'Storry Photography']);" class="widget_sp_image-image-link "><img alt="" class="aligncenter" width="200" src="http://www.loveluxeblog.com//adverts_temp_store/26d0a3c3bb9ac416d4d24bcf23a601a6/1357566276_Love-Luxe-Blog-200-x-90-Advert.jpg"></a>
                                                                                                                                                                                               <a target="_blank" href="http://www.mattnolanphotography.co.uk" onclick="_gaq.push(['_trackEvent', 'Sidebar Advert', 'Click', 'matt nolan photography']);" class="widget_sp_image-image-link "><img alt="" class="aligncenter" width="200" src="http://www.loveluxeblog.com//adverts_temp_store/69851a52b91fb395c4800f74a76a2998/1344545536_matt-nolan-photography-200x90.jpg"></a>
                                                                                                                                                                                               <a target="_blank" href="http://www.lydiastampsphotography.com" onclick="_gaq.push(['_trackEvent', 'Sidebar Advert', 'Click', 'Lydia Stamps Photography']);" class="widget_sp_image-image-link "><img alt="" class="aligncenter" width="200" src="http://www.loveluxeblog.com//adverts_temp_store/ec0b0e4c6d89a6d64eb1e48424e79eab/1351529710_LoveLuxeLSPhotoAd.jpg"></a>
                                                                                                                                                                                               <a target="_blank" href="http://www.etsy.com/shop/VintageLovesRoses?ref=si_shop" onclick="_gaq.push(['_trackEvent', 'Sidebar Advert', 'Click', 'Vintage Loves Roses']);" class="widget_sp_image-image-link "><img alt="" class="aligncenter" width="200" src="http://www.loveluxeblog.com//adverts_temp_store/7b77a39e1105a78b5e9f83ed2e14517b/1354623597_Love%20Luxe%20blog-01.png"></a>
                                                                                                                                                                                               <a target="_blank" href="http://www.lilyandfrank.co.uk" onclick="_gaq.push(['_trackEvent', 'Sidebar Advert', 'Click', 'Lily & Frank Photography']);" class="widget_sp_image-image-link "><img alt="" class="aligncenter" width="200" src="http://www.loveluxeblog.com//adverts_temp_store/5416607f8fb96d8bb597e4f07db827bf/1353236046_loveluxe.jpg"></a>
                                                                                                                                                                                               <a target="_blank" href="http://www.sarahvivienne.co.uk/" onclick="_gaq.push(['_trackEvent', 'Sidebar Advert', 'Click', 'Sarah Vivienne Photography']);" class="widget_sp_image-image-link "><img alt="" class="aligncenter" width="200" src="http://www.loveluxeblog.com//adverts_temp_store/c2d2e3867b511988bdfee842ece80b39/1344255496_Wedding%20photographer%20Northampton%20Sarah%20Vivienne.jpg"></a>
                                                                                                                                                                                               <a target="_blank" href="http://lolarosephotography.com" onclick="_gaq.push(['_trackEvent', 'Sidebar Advert', 'Click', 'Lola Rose Photography']);" class="widget_sp_image-image-link "><img alt="" class="aligncenter" width="200" src="http://www.loveluxeblog.com//adverts_temp_store/90e5d05b60283d429c34b39960e4265d/1356956773_Lola%20Rose%20Love%20Luxe%20Ad%201.jpg"></a>
                                                                                                                                                                                               <a target="_blank" href="http://www.etsy.com/shop/MintAfternoon" onclick="_gaq.push(['_trackEvent', 'Sidebar Advert', 'Click', 'Mint Afternoon']);" class="widget_sp_image-image-link "><img alt="" class="aligncenter" width="200" src="http://www.loveluxeblog.com//adverts_temp_store/mint/AD3.png"></a>
                                                                                                                                                                                               <a target="_blank" href="http://www.evedunlopphotography.co.uk" onclick="_gaq.push(['_trackEvent', 'Sidebar Advert', 'Click', 'eve dunlop Photography']);" class="widget_sp_image-image-link "><img alt="" class="aligncenter" width="200" src="http://www.loveluxeblog.com//adverts_temp_store/7f3e19167b3c6743a878e83895bc7d02/1355845749_blogpic.jpg"></a>
                                                                                                                                                                                               <a target="_blank" href="http://www.bride-electric.com/" onclick="_gaq.push(['_trackEvent', 'Sidebar Advert', 'Click', 'Bride Electric']);" class="widget_sp_image-image-link no-mg-bottom"><img alt="" class="aligncenter" width="200" src="http://www.loveluxeblog.com//adverts_temp_store/bride-electric/bride-electric.jpg"></a>
                                                                                                                                                                                               <a target="_blank" href="http://www.maureendupreez.com" onclick="_gaq.push(['_trackEvent', 'Sidebar Advert', 'Click', 'Maureen Du Preez Photography']);" class="widget_sp_image-image-link no-mg-bottom"><img alt="" class="aligncenter" width="200" src="http://www.loveluxeblog.com//adverts_temp_store/4c21d865cd9bb6080fa164abd1c527be/1352224904_loveluxebutton.jpg"></a>        </aside>
                                                                                                                                                                                               </div>
                                                                                                                                                                                               </section></div></div></div><div class="go-home"><a id="go-to-top" href="#">to the top</a></div>
                                                                                                                                                                                               </div>
                                                                                                                                                                                               <footer role="contentinfo">
                                                                                                                                                                                               <div class="f-bg"></div>
                                                                                                                                                                                               <p class="credit-warning">We have taken all efforts to request permission for all images featured on this site and to link back to the original source. However if we have used your images and you think we have not credited you please let us know as we will rectify it asap, or at your request we can remove the images. Thank you!</p>
                                                                                                                                                                                               <div class="f-wrap">
                                                                                                                                                                                               <nav class="f-cats"><h5>Popular Posts</h5><ul><li><a href="http://www.loveluxeblog.com/parties-a-simple-wedding-anniversary-dinner/" class="stack-img"><img width="50" height="50" src="/cache/uploads/2012/06/small-thumb-1789-50-anniversary-dinner-06.jpg" alt="Parties: A Simple Wedding Anniversary Dinner" class="wp-post-image s-tmb" /></a><a class="link" href="http://www.loveluxeblog.com/parties-a-simple-wedding-anniversary-dinner/">Parties: A Simple Wedding Anniversary Dinner</a></li></ul></nav>
                                                                                                                                                                                               <nav class="f-cats"><h5>Recent Posts</h5><ul><li><a href="http://www.loveluxeblog.com/cakes-and-desserts-my-diy-wedding-cake/" class="stack-img"><img width="50" height="50" src="/cache/uploads/2013/02/small-thumb-7753-50-LoveLuxe-Post01-BB-FeaturedPic2.jpg" alt="Cakes and Desserts: My DIY wedding cake" class="wp-post-image s-tmb" /></a><a class="link" href="http://www.loveluxeblog.com/cakes-and-desserts-my-diy-wedding-cake/">Cakes and Desserts: My DIY wedding cake</a></li><li><a href="http://www.loveluxeblog.com/planning-a-wedding-on-a-tight-budget-advice-from-a-wedding-planner-and-tips-from-a-real-bride/" class="stack-img"><img width="50" height="50" src="/cache/uploads/2013/01/small-thumb-7569-50-donated-flowers.jpg" alt="Planning a wedding on a tight budget: advice from a wedding planner" class="wp-post-image s-tmb" /></a><a class="link" href="http://www.loveluxeblog.com/planning-a-wedding-on-a-tight-budget-advice-from-a-wedding-planner-and-tips-from-a-real-bride/">Planning a wedding on a tight budget: advice from a wedding planner</a></li><li><a href="http://www.loveluxeblog.com/planning-a-wedding-in-france-introducing-the-amour-list/" class="stack-img"><img width="50" height="50" src="/cache/uploads/2013/01/small-thumb-7040-50-amour-list.jpg" alt="Planning a wedding in France? Introducing The Amour List!" class="wp-post-image s-tmb" /></a><a class="link" href="http://www.loveluxeblog.com/planning-a-wedding-in-france-introducing-the-amour-list/">Planning a wedding in France? Introducing The Amour List!</a></li><li><a href="http://www.loveluxeblog.com/free-printables-an-invitation-to-celebrate/" class="stack-img"><img width="50" height="50" src="/cache/uploads/2013/01/small-thumb-7396-50-Printable-Party-Invitation-Delectable-Ink-LoveLuxeBlog.jpg" alt="Free Printables: An Invitation to Celebrate!" class="wp-post-image s-tmb" /></a><a class="link" href="http://www.loveluxeblog.com/free-printables-an-invitation-to-celebrate/">Free Printables: An Invitation to Celebrate!</a></li><li><a href="http://www.loveluxeblog.com/winter-white-wedding-style/" class="stack-img"><img width="50" height="50" src="/cache/uploads/2013/01/small-thumb-7083-50-single-featured-7083-660-snowflake-boomark.jpg" alt="Winter White Wedding Style" class="wp-post-image s-tmb" /></a><a class="link" href="http://www.loveluxeblog.com/winter-white-wedding-style/">Winter White Wedding Style</a></li></ul></nav>
                                                                                                                                                                                               <nav class="social-nav">
                                                                                                                                                                                               <a class="pinterest" href="http://www.pinterest.com/LoveLuxeBlog/"></a>
                                                                                                                                                                                               <a class="facebook" href="http://www.facebook.com/LoveLuxeBlog/"></a>
                                                                                                                                                                                               <a class="twitter" href="http://twitter.com/LoveLuxeBlog/"></a>
                                                                                                                                                                                               <a class="rss" href="http://www.loveluxeblog.com/feed/"></a>
                                                                                                                                                                                               </nav>
                                                                                                                                                                                               <section class="f-search">
                                                                                                                                                                                               <form class="searchform" method="get" id="searchform_footer" action="http://www.loveluxeblog.com/">
                                                                                                                                                                                               <label for="search-words_footer" class="assistive-text">Search</label>
                                                                                                                                                                                               <input type="text" class="field" name="s" id="search-words_footer" placeholder="Search..." />
                                                                                                                                                                                               <input type="submit" class="submit" name="submit" id="searchsubmit_footer" value="Search" />
                                                                                                                                                                                               </form>                    </section>
                                                                                                                                                                                               </div>
                                                                                                                                                                                               </footer>
                                                                                                                                                                                               <script type="text/javascript" src="//assets.pinterest.com/js/pinit.js"></script><script type="text/javascript">/*<![CDATA[*/
                                                                                                                                                                                               pinitRender = function() {
                                                                                                                                                                                               (function (w, d, load) {
                                                                                                                                                                                                var script,
                                                                                                                                                                                                first = d.getElementsByTagName('SCRIPT')[0],  
                                                                                                                                                                                                n = load.length,
                                                                                                                                                                                                i = 0,
                                                                                                                                                                                                go = function () {
                                                                                                                                                                                                for (i = 0; i < n; i = i + 1) {
                                                                                                                                                                                                script = d.createElement('SCRIPT');
                                                                                                                                                                                                script.type = 'text/javascript';
                                                                                                                                                                                                script.async = true;
                                                                                                                                                                                                script.src = load[i];
                                                                                                                                                                                                first.parentNode.insertBefore(script, first);
                                                                                                                                                                                                }
                                                                                                                                                                                                }
                                                                                                                                                                                                if (w.attachEvent) {
                                                                                                                                                                                                w.attachEvent('onload', go);
                                                                                                                                                                                                } else {
                                                                                                                                                                                                w.addEventListener('load', go, false);
                                                                                                                                                                                                }
                                                                                                                                                                                                }(window, document,
                                                                                                                                                                                                  ['//assets.pinterest.com/js/pinit.js']
                                                                                                                                                                                                  ));    
                                                                                                                                                                                               }
/*]]>*/</script>
                                                                                                                                                                                               </body>
                                                                                                                                                                                               </html>